### ISSUE TITLE
typestring(): delay arg default value is not working properly

### ISSUE THREAD

**Issue by mlamarin** [pmur002/xdotool#1]
Dear Paul,

I hope you had a nice Xmas break and thanks again for all the achievements you did so far for the data scientist community.
I just found your tiny but nice package on the top of xdotool. 
It seems that the **delay** arg in the **typestring** function is not handled properly by the mapply call.

Best Regards
Marc

> library(xdotool)
> typestring('R is great!')
Error in mapply(function(s, d) { : 
  zero-length inputs cannot be mixed with those of non-zero length
>
> typestring('R is great!', 12)
R is great!

> packageDescription('xdotool')
Package: xdotool
Type: Package
Title: R interface to xdotool command
Version: 0.1-2
Date: 2016-11-25
Author: Paul Murrell
Maintainer: Paul Murrell <paul@stat.auckland.ac.nz>
Description: Provides R functions to simulate keyboard and mouse
        actions on a Linux desktop (with an X Window manager that is
        compatible with the EWMH/NetWM specification). The functions
        all work by making system calls to the xdotool command.
License: file LICENSE
SystemRequirements: xdotool
RemoteType: github
RemoteHost: api.github.com
RemoteRepo: xdotool
RemoteUsername: pmur002
RemoteRef: HEAD
RemoteSha: d25beab15cad0b40198df8fee18b6fc7ccb5550a
GithubRepo: xdotool
GithubUsername: pmur002
GithubRef: HEAD
GithubSHA1: d25beab15cad0b40198df8fee18b6fc7ccb5550a
NeedsCompilation: no
Packaged: 2022-12-28 11:40:58 UTC; root
Built: R 4.1.3; ; 2022-12-28 11:40:58 UTC; unix

**Comment by pmur002** [comment]
Thanks very much for the report.  I have committed what I hope is a fix.

**Comment by mlamarin** [comment]
Hello Paul
Many thanks, it works, I just tested it. I think we are good
Have a nice day. 
All the best
Marc

**Comment by pmur002** [comment]
Great.  Thanks for confirming.
